#activity:
#  - type: travel
#    fields:
#      - name: city
#        question: 哪个城市？| 城市？
#        optional: false
#      - name: attraction
#        question: 哪个景点？
#        optional: true
#      - name: date
#        question: 什么时候？
#        optional: false
#        format:   # 可以限定格式
#  - type: sport
#    fields:
#      - name: city
#        question: 哪个城市？
#        optional: false
#      - name: name
#        question: 什么运动？
#        optional: true
#        options: 篮球,羽毛球,乒乓球   # 可以增加默认选项
#
##